const GameServer = require('../GameServer');
const Aircraft = require('../Aircraft');
const ConflictDetector = require('../ConflictDetector');

// Mock db to avoid writing to SQLite in test environment
jest.mock('../../db', () => ({
    logAircraftState: jest.fn(),
    getAllLogs: jest.fn()
}));

// Provide deterministic IDs
jest.mock('uuid', () => ({
    v4: jest.fn(() => 'test-uuid-1234')
}));

describe('GameServer Integration Tests', () => {
    let ioMock;
    let gameServer;

    beforeEach(() => {
        // Mock socket.io implementation
        ioMock = {
            emit: jest.fn()
        };
        gameServer = new GameServer(ioMock);
    });

    test('Integration: GameServer correctly spawns and tracks aircraft components', () => {
        // Initial setup inside GameServer constructor spawns 2 aircraft
        expect(gameServer.aircrafts.size).toBeGreaterThanOrEqual(2);
        
        // Spawn an explicit instance
        gameServer.spawnAircraft('ARRIVAL');
        const newAircraft = gameServer.aircrafts.get('test-uuid-1234');
        
        expect(newAircraft).toBeInstanceOf(Aircraft);
        expect(newAircraft.type).toBe('ARRIVAL');
    });

    test('Integration: ConflictDetector resolves conflicts generated by GameServer loops', () => {
        gameServer.aircrafts.clear(); // Clear default spawns

        // Inject 2 aircraft very close to each other
        const a1 = new Aircraft('ID_1', 'ARRIVAL', gameServer);
        a1.x = 100;
        a1.y = 100;
        a1.state = 'AIRBORNE';

        const a2 = new Aircraft('ID_2', 'ARRIVAL', gameServer);
        a2.x = 105; // Less than separation minima
        a2.y = 100;
        a2.state = 'AIRBORNE';

        gameServer.aircrafts.set('ID_1', a1);
        gameServer.aircrafts.set('ID_2', a2);

        // Run ConflictDetector through game server instance
        const conflicts = gameServer.conflictDetector.checkConflicts();
        expect(conflicts.length).toBe(1);
        expect(conflicts[0].a1.id).toBe('ID_1');
        expect(conflicts[0].a2.id).toBe('ID_2');
    });

    test('Integration: Validating LAND command locks specific integrated Runway class', () => {
        const testAircraftId = 'test-uuid-1234';
        gameServer.spawnAircraft('ARRIVAL');
        const aircraft = gameServer.aircrafts.get(testAircraftId);

        // State changes to simulate landing sequence
        aircraft.state = 'APPROACH';

        // Issue Integrated Command Request
        gameServer.handleCommand({
            type: 'LAND',
            aircraftId: testAircraftId,
            payload: { runwayId: '09L' }
        });

        // Verify System Integration Response: Runway is successfully occupied
        const runway = gameServer.runways.get('09L');
        expect(runway.status).toBe('OCCUPIED');
        expect(runway.occupiedBy).toBe(testAircraftId);
    });
});
